// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ4Ql_OEsThZ7bk1Obsml3j-V5itVRkMA',
    appId: '1:803502112825:web:949455ab5b62e737624de8',
    messagingSenderId: '803502112825',
    projectId: 'fir-flutter-kata',
    authDomain: 'fir-flutter-kata.firebaseapp.com',
    storageBucket: 'fir-flutter-kata.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1Kr6DJeJGi9xECDX_FSwMbJPcv7pbasU',
    appId: '1:803502112825:android:78a878927823c740624de8',
    messagingSenderId: '803502112825',
    projectId: 'fir-flutter-kata',
    storageBucket: 'fir-flutter-kata.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi23-S6wRHahgayNQwPh-Bb5aXkCDM-Fg',
    appId: '1:803502112825:ios:22d115ed473ba9e2624de8',
    messagingSenderId: '803502112825',
    projectId: 'fir-flutter-kata',
    storageBucket: 'fir-flutter-kata.firebasestorage.app',
    iosBundleId: 'com.example.firebaseflutterkata.firebaseFlutterKata',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi23-S6wRHahgayNQwPh-Bb5aXkCDM-Fg',
    appId: '1:803502112825:ios:22d115ed473ba9e2624de8',
    messagingSenderId: '803502112825',
    projectId: 'fir-flutter-kata',
    storageBucket: 'fir-flutter-kata.firebasestorage.app',
    iosBundleId: 'com.example.firebaseflutterkata.firebaseFlutterKata',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZ4Ql_OEsThZ7bk1Obsml3j-V5itVRkMA',
    appId: '1:803502112825:web:e33702ef30f5d812624de8',
    messagingSenderId: '803502112825',
    projectId: 'fir-flutter-kata',
    authDomain: 'fir-flutter-kata.firebaseapp.com',
    storageBucket: 'fir-flutter-kata.firebasestorage.app',
  );
}
